### ISSUE TITLE
Special characters not handled properly on all OS

### ISSUE THREAD

**Issue by rlavendomme** [jmaglic/MoloVol#27]
In a previous build (ffbf7b2 ) using unicode chars in wstrings, everything was displayed perfectly on Windows 10 and I believe there was no issue with other OS.

In the later build including special_chars.cpp to display special chars from UTF-8 encoded strings (build 060785c ), there are two issues for me on Windows 10:
1) the code wouldn't compile (missing the header cassert in special_chars.cpp)
2) special characters handled by special_chars.cpp are not displayed properly
![image](https://user-images.githubusercontent.com/65511614/90678688-4ffd6b00-e25f-11ea-91b1-f4156e1b7c72.png)

You can see that one angström symbol is displayed properly after Grid step size in the parameter panel. This is because it is still handled as I implemented it with unicode char in wstring.
See line 289 in base_init.cpp
`gridsizeUnitText = new wxStaticText(gridsizeInputPanel, TEXT_Gridunit, L"\u212B "); // unicode for angstrom`
Note that the unicode character is also present in the atom list grid not shown in the picture, see line 332 of base_init.cpp
`  atomListGrid->SetColLabelValue(3, L"Radius (\u212B)");`

Considering the issue (I don't know its cause yet), is it still preferable to use UTF-8 encoded strings instead of unicode characters in wstring if it was working perfectly fine for all OS? (we don't need many occurrences in the program anyway)

**Comment by rlavendomme** [comment]
After a quick search, it seems that UTF-8 characters are not natively supported by windows console. It seems possible on windows 10 to set the console output in UTF-8 but it is not as straightforward for windows 7 (which is still commonly used).
I would suggest to use a solution supporting as many OS as possible since it is one of the purposes of this program.

**Comment by jmaglic** [comment]
The issue with wstring is that it's incompatible with string. Converting one to the other made the code incredibly messy for me. Having an overloaded function for every string function is bloat. There has to be a better way that using wstring.

**Comment by rlavendomme** [comment]
> Having an overloaded function for every string function is bloat. 

You're saying that as we would have many overloaded string functions but I can only see two: one for the output panel and a future function that will deal with output file report.

**Comment by jmaglic** [comment]
This may be a different issue but I think it would be best to avoid special symbols in the output text file.

**Comment by rlavendomme** [comment]
> 
> 
> This may be a different issue but I think it would be best to avoid special symbols in the output text file.

I thought unicode formated txt files were common enough to not be problematic.
In any case, we can easily do without special characters:
- A^3 for cubic angstrom
- A^2 for squared angstrom
- normal numbers instead of subscripts
I believe these are the only three uses of special characters that we would have needed.

**Comment by jmaglic** [comment]
Exactly, that is what I was thinking.

As for the special characters, I will try to just use wxWidget's wxString to make it work.

**Comment by rlavendomme** [comment]
> As for the special characters, I will try to just use wxWidget's wxString to make it work.

Sounds good. I already thought about this possibility. The only thing to be careful about it to keep all wxWidget dependencies in the front-end and controller but not in the back-end to insure portability of the back-end code to other programs not using wxWidgets.

**Comment by rlavendomme** [comment]
Since merge #62 I believe all special characters in output (notification box and report) were replaced by ASCII characters.
We could delete the special characters dedicated source and header files `special_chars.cpp` and `special_chars.h` that are obsolete and close this issue.

**Comment by jmaglic** [comment]
But there is still the issue of Å³ being written as A^3. I thought this was just a momentary work around? I find this very ugly and would be against leaving it like this. The existing code could be reused once we find an encoding that works on all platforms.

**Comment by rlavendomme** [comment]
> 
> 
> I thought this was just a momentary work around? 

I misunderstood you. I thought you preferred to avoid unicode characters altogether because the report files should only use ASCII characters.

Well, we had a working solution with the overloaded function using wstring for unicode characters.
Otherwise, the Å is in the extended ASCII character table (Alt+143). I don't know if superscript number are also available outside unicode characters.
