### ISSUE TITLE
Guide for ubuntu

### ISSUE THREAD

**Issue by BSVogler** [jmaglic/MoloVol#51]
I was asked to provide my experience with installing this software on ubuntu. Please use this knowledge for the guides.
The GUI functionality was not working and the software unusable. This might have been caused by using the development version wxwidget3.14 or libgtk-3-dev. 

There might be steps missing in the guide below.
### To compile wxwidgets
Download
[https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.tar.bz2](https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.4/wxWidgets-3.1.4.tar.bz2)
Install dependencies
`sudo apt-get install libgtk-3-dev`

Compile wxwidget

`mkdir build`
`cd build`
`../configure`
`make`
`sudo make install`

**Comment by jmaglic** [comment]
I've added a [Linux set-up guide to the wiki](https://github.com/jmaglic/MoloVol/wiki/Getting-started-on-Linux). This has worked perfectly for me. The app compiles fine and all functionalities seem intact.
